export const headlines: string[] = [
  "SHRIVAS DECLARES MOVE TO NETHERLANDS — CONSOLE SHIPS WITH HIM",
  "LOCAL TEEN REFUSES TO SHIP A MEDIOCRE WEBSITE, THIRD YEAR RUNNING",
  "ENTØ STUDIOS TURNS ONE MONTH OLD, DEMANDS CAKE",
  "SCIENTISTS CONFIRM: CLICKING AROUND UNLOCKS SECRETS",
  "COIMBATORE EXPORTS: FILTER COFFEE, FOUNDERS",
  "SYSTEM REPORTS 0 TEMPLATES USED IN THE MAKING OF THIS SITE",
];
