export const headlines: string[] = [
  "SHRIVAS DECLARES MOVE TO NETHERLANDS — CONSOLE SHIPS WITH HIM",
  "LOCAL TEEN REFUSES TO SHIP A MEDIOCRE WEBSITE, THIRD YEAR RUNNING",
  "ENTØ STUDIOS TURNS ONE MONTH OLD, DEMANDS CAKE",
  "SCIENTISTS CONFIRM: CLICKING AROUND UNLOCKS SECRETS",
  "COIMBATORE EXPORTS: FILTER COFFEE, FOUNDERS",
  "SYSTEM REPORTS 0 TEMPLATES USED IN THE MAKING OF THIS SITE",
  "ENTØ ACCEPTING QUESTS — SERIOUS INQUIRIES TO THE STUDIO CABLE",
  "MOM RATES FIRST WEBSITE FIVE STARS, CITES BIAS",
  "SHUTTLECOCK PHYSICS DECLARED 'FLOATY IN A GOOD WAY' BY LOCAL EXPERTS",
  "STICKY NOTE CAUGHT CYCLING HINTS, DENIES EVERYTHING",
  "100% SPEEDRUN RECORD REMAINS UNCLAIMED",
  "CURSOR NOW PIXELATED — PRODUCTIVITY MIRACULOUSLY UNAFFECTED",
];

/** one extra headline that knows what time it is */
export function timeHeadline(hour: number): string | null {
  if (hour >= 0 && hour < 5)
    return "SHRIVAS IS PROBABLY ALSO AWAKE RIGHT NOW";
  if (hour >= 5 && hour < 11)
    return "CONSOLE REPORTS: FILTER COFFEE REQUIRED BEFORE FURTHER INPUT";
  if (hour >= 23) return "THE CONSOLE DOES NOT SLEEP. NEITHER DOES ITS OWNER";
  return null;
}
